### PR TITLE
First code

### PR DESCRIPTION
**Pull request by cfelde**
Getting started with a functioning demo

### CODE REVIEW

**Comment by ligi** [comment]
just wondering why you add all these libs as jars

**Comment by cfelde** [comment]
Currently just dumping all Hyperledger Besu jars, including libs it needs into there. That's obviously not ideal, so we'll clean this up, but want to get the outstanding RPCs done first.

**Comment by ligi** [comment]
can't you drag in the dependencies via e.g. jitpack?

**Comment by cfelde** [comment]
Yeah, maybe, worth looking at.

**Pull request merged**
